# railway.toml
[build]
# Tentukan command untuk build aplikasi Anda
# Misalnya, Anda mungkin ingin menjalankan migrasi dan install dependencies
commands = [
  "composer install --optimize-autoloader --no-dev",
  "php artisan migrate:fresh --seeds",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "npm install"
]

# Tentukan direktori tempat aplikasi Anda berada, jika aplikasi Anda berada di root, biarkan kosong atau hapus baris ini
context = ""

[deploy]
# Tentukan command untuk menjalankan aplikasi Anda
commands = [
  "php artisan serve"
]
